### ISSUE TITLE
Water Quality interface wont push data to table See warning

### ISSUE THREAD

**Issue by bumpersp** [mkleinha/sqlite_interface#4]
@mkleinha  
cannot coerce type 'closure' to vector of type 'character'

From my reading this often arises when a function is being called when you actually want the output of the function. I can't find where this might be the case. Could use some help debugging this or tips on how to approach this as the code is quite long now. Probably should divy this code up? 

See the WQ_gui_branch for the waterquality_entryform_draft script

**Comment by mkleinha** [comment]
The error was thrown by the call to gsub() on line 96. It's due to inconsistent capitalization between function parameter names and user input id's in the original script, bad coding practice on my part. The parameter to update_hab() used to be 'date'. Now it's 'Date'. Capitalizing 'date' on line 96 resolved the error for me.

**Comment by bumpersp** [comment]
Cool. Was there a red X on the left side that I missed or you're just that good? That seems to have fixed that error on my part.
