### ISSUE TITLE
Master branch

### ISSUE THREAD

**Issue by knconnelly** [mkleinha/sqlite_interface#7]
What's the status of the master branch?  Could we upload @mkleinha's updated version of the updated database file and 'taxonomy_lookup' table reference?

**Comment by mkleinha** [comment]
I was going to try to keep the database itself off the github repo. I had originally included it, but it lead to hard-to-resolve merge conflicts and long upload and download times due to the size of the file. I think it would be simplest to stick to tracking text files with git and interacting with the database by either maintaining a local copy or pointing to the version on the RBC drive. I am open to suggestions though.  The most up-to-date version on the master branch should reference the 'taxonomy_lookup' table. The version of the database including these new tables can be found in the same place on the RBC drive. Does this answer your questions?

**Comment by bumpersp** [comment]
I agree. Let's keep the databases themselves off of github. I accidentally copied the empty water quality one but we can delete it.

**Comment by knconnelly** [comment]
I guess I meant the updated code, not database, my bad.  And yeah, that answers my question about the master branch.
